service: farmer
image: studio-kare/farmer

servers:
  web:
    hosts:
      - 163.172.149.152

registry:
  server: rg.fr-par.scw.cloud
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: root
  keys:
    - ./dev-instance-key

builder:
  remote: ssh://root@163.172.149.152
  arch: amd64

proxy:
  ssl: true
  host: router.studiokare.nl
  app_port: 3000
  healthcheck:
    path: /health
    interval: 3
    timeout: 3

env:
  clear:
    DEPLOYMENT: public
    PUBLIC_DAILY_POOL: "10000000"
  secret:
    - PUBLIC_API_KEY
    - PUBLIC_ADMIN_TOKEN
    - OPENAI_API_KEY
    - ANTHROPIC_API_KEY
    - OPENROUTER_API_KEY
    - AZURE_OPENAI_API_KEY
    - AZURE_OPENAI_ENDPOINT

volumes:
  - "farmer-data:/app/data"
